from learning_to_rank import execute

if __name__ == '__main__':
    print execute('', 'localhost',
                  '3306',
                  'root',
                  'root',
                  'test',
                  'crime',
                  "SELECT * FROM crime",
                  'ID',
                  "Case Number",
                  'Date',
                  'Block',
                  'IUCR',
                  "Primary Type",
                  'Description',
                  "Location Description",
                  'Arrest',
                  'Domestic',
                  'Beat',
                  'District',
                  'Ward',
                  "Community Area",
                  "FBI Code",
                  'Latitude',
                  'Longitude',
                  'Location',
                  'int(20)',
                  'varchar(255)',
                  'datetime',
                  'varchar(255)',
                  'varchar(255)',
                  'varchar(255)',
                  'varchar(255)',
                  'varchar(255)',
                  'int(11)',
                  'int(11)',
                  'varchar(11)',
                  'varchar(11)',
                  'varchar(11)',
                  'varchar(11)',
                  'varchar(255)',
                  'float',
                  'float',
                  'varchar(255)')
